USE [master]
GO

/****** Object:  Database [RealEstateDb]    Script Date: 23-07-2022 14:29:52 ******/
CREATE DATABASE [RealEstateDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'RealEstateDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\RealEstateDb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'RealEstateDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\RealEstateDb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [RealEstateDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [RealEstateDb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [RealEstateDb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [RealEstateDb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [RealEstateDb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [RealEstateDb] SET ARITHABORT OFF 
GO

ALTER DATABASE [RealEstateDb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [RealEstateDb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [RealEstateDb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [RealEstateDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [RealEstateDb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [RealEstateDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [RealEstateDb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [RealEstateDb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [RealEstateDb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [RealEstateDb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [RealEstateDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [RealEstateDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [RealEstateDb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [RealEstateDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [RealEstateDb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [RealEstateDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [RealEstateDb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [RealEstateDb] SET RECOVERY FULL 
GO

ALTER DATABASE [RealEstateDb] SET  MULTI_USER 
GO

ALTER DATABASE [RealEstateDb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [RealEstateDb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [RealEstateDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [RealEstateDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [RealEstateDb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [RealEstateDb] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [RealEstateDb] SET QUERY_STORE = OFF
GO

ALTER DATABASE [RealEstateDb] SET  READ_WRITE 
GO


